<a href="https://colab.research.google.com/github/Jigyasa-sharma7/Pollution-Level-Forecasting/blob/main/pollution_forecasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import glob
import os

In [ ]:
files = glob.glob("/content/*.csv")

print("Number of CSV files:", len(files))

for file in files:
    print(os.path.basename(file))

Number of CSV files: 12
PRSA_Data_Nongzhanguan_20130301-20170228.csv
PRSA_Data_Dingling_20130301-20170228.csv
PRSA_Data_Guanyuan_20130301-20170228.csv
PRSA_Data_Changping_20130301-20170228.csv
PRSA_Data_Wanshouxigong_20130301-20170228.csv
PRSA_Data_Wanliu_20130301-20170228.csv
PRSA_Data_Aotizhongxin_20130301-20170228.csv
PRSA_Data_Gucheng_20130301-20170228.csv
PRSA_Data_Huairou_20130301-20170228.csv
PRSA_Data_Shunyi_20130301-20170228.csv
PRSA_Data_Dongsi_20130301-20170228.csv
PRSA_Data_Tiantan_20130301-20170228.csv

In [ ]:
df_list = []

for file in files:
    temp_df = pd.read_csv(file)
    df_list.append(temp_df)

df = pd.concat(df_list, ignore_index=True)

print("Dataset shape:", df.shape)

Dataset shape: (420768, 18)

In [ ]:
df.head()

,No,year,month,day,hour,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,wd,WSPM,station
0,1,2013,3,1,0,5.0,14.0,4.0,12.0,200.0,85.0,-0.5,1024.5,-21.4,0.0,NNW,5.7,Nongzhanguan
1,2,2013,3,1,1,8.0,12.0,6.0,14.0,200.0,84.0,-0.7,1025.1,-22.1,0.0,NW,3.9,Nongzhanguan
2,3,2013,3,1,2,3.0,6.0,5.0,14.0,200.0,83.0,-1.2,1025.3,-24.6,0.0,NNW,5.3,Nongzhanguan
3,4,2013,3,1,3,5.0,5.0,5.0,14.0,200.0,84.0,-1.4,1026.2,-25.5,0.0,N,4.9,Nongzhanguan
4,5,2013,3,1,4,5.0,5.0,6.0,21.0,200.0,77.0,-1.9,1027.1,-24.5,0.0,NNW,3.2,Nongzhanguan

In [ ]:
df.columns.tolist()

['No',
 'year',
 'month',
 'day',
 'hour',
 'PM2.5',
 'PM10',
 'SO2',
 'NO2',
 'CO',
 'O3',
 'TEMP',
 'PRES',
 'DEWP',
 'RAIN',
 'wd',
 'WSPM',
 'station']

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 420768 entries, 0 to 420767
Data columns (total 18 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   No       420768 non-null  int64
 1   year     420768 non-null  int64
 2   month    420768 non-null  int64
 3   day      420768 non-null  int64
 4   hour     420768 non-null  int64
 5   PM2.5    412029 non-null  float64
 6   PM10     414319 non-null  float64
 7   SO2      411747 non-null  float64
 8   NO2      408652 non-null  float64
 9   CO       400067 non-null  float64
 10  O3       407491 non-null  float64
 11  TEMP     420370 non-null  float64
 12  PRES     420375 non-null  float64
 13  DEWP     420365 non-null  float64
 14  RAIN     420378 non-null  float64
 15  wd       418946 non-null  object
 16  WSPM     420450 non-null  float64
 17  station  420768 non-null  object
dtypes: float64(11), int64(5), object(2)
memory usage: 57.8+ MB

In [ ]:
print(df.shape)
print(df.columns.tolist())

(420768, 18)
['No', 'year', 'month', 'day', 'hour', 'PM2.5', 'PM10', 'SO2', 'NO2', 'CO', 'O3', 'TEMP', 'PRES', 'DEWP', 'RAIN', 'wd', 'WSPM', 'station']

In [9]:
missing = df.isnull().sum()

print(missing)

No             0
year           0
month          0
day            0
hour           0
PM2.5       8739
PM10        6449
SO2         9021
NO2        12116
CO         20701
O3         13277
TEMP         398
PRES         393
DEWP         403
RAIN         390
wd          1822
WSPM         318
station        0
dtype: int64

In [10]:
missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_table = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Missing Percentage": missing_percentage
})

missing_table.sort_values("Missing Percentage", ascending=False)

         Missing Values  Missing Percentage
CO                20701            4.919813
O3                13277            3.155421
NO2               12116            2.879497
SO2                9021            2.143937
PM2.5              8739            2.076916
PM10               6449            1.532674
wd                 1822            0.433018
DEWP                403            0.095777
TEMP                398            0.094589
PRES                393            0.093401
RAIN                390            0.092688
WSPM                318            0.075576
year                  0            0.000000
No                    0            0.000000
day                   0            0.000000
month                 0            0.000000
hour                  0            0.000000
station               0            0.000000

In [11]:
print("Number of stations:", df["station"].nunique())
print("\nStations:")
print(df["station"].unique())

Number of stations: 12

Stations:
['Nongzhanguan' 'Dingling' 'Guanyuan' 'Changping' 'Wanshouxigong' 'Wanliu'
 'Aotizhongxin' 'Gucheng' 'Huairou' 'Shunyi' 'Dongsi' 'Tiantan']

In [13]:
print(df["PM2.5"].describe())
print("Missing PM2.5:", df["PM2.5"].isnull().sum())

count    412029.000000
mean         79.793428
std          80.822391
min           2.000000
25%          20.000000
50%          55.000000
75%         111.000000
max         999.000000
Name: PM2.5, dtype: float64
Missing PM2.5: 8739

We check the 999 value is actually a max value or an invalid value

In [15]:
print("PM2.5 values equal to 999:", (df["PM2.5"] == 999).sum())
print("PM10 values equal to 999:", (df["PM10"] == 999).sum())
print("CO values equal to 999:", (df["CO"] == 999).sum())
print("NO2 values equal to 999:", (df["NO2"] == 999).sum())
print("SO2 values equal to 999:", (df["SO2"] == 999).sum())
print("O3 values equal to 999:", (df["O3"] == 999).sum())

PM2.5 values equal to 999: 1
PM10 values equal to 999: 3
CO values equal to 999: 0
NO2 values equal to 999: 0
SO2 values equal to 999: 0
O3 values equal to 999: 0

In [16]:
df[df["PM2.5"] == 999][["station", "year", "month", "day", "hour", "PM2.5"]].head(20)

              station  year  month  day  hour  PM2.5
166034  Wanshouxigong  2016      2    8     2  999.0

We will replace the 999 values as we can conclude that they are invalid values and not a maximumvalue of our target variable

In [17]:
pollution_cols = ["PM2.5", "PM10", "CO", "NO2", "SO2", "O3"]

for col in pollution_cols:
    df[col] = df[col].replace(999, pd.NA)

In [18]:
for col in pollution_cols:
    print(f"{col} missing values:", df[col].isna().sum())

PM2.5 missing values: 8740
PM10 missing values: 6452
CO missing values: 20701
NO2 missing values: 12116
SO2 missing values: 9021
O3 missing values: 13277

We will not replace the missing values of the target variable with mean or median as it is only 2% missing values and we can delete the whole rows where PM2.5 have missing values also we have many rows so 2% reduction will not affect out model

In [19]:
df_model = df.dropna(subset=["PM2.5"]).copy()